[package]
name = "easy-imgui-window"
version = "0.1.0"
edition = "2021"

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]

[dependencies]
easy-imgui-sys = { path = "../easy-imgui-sys" }
easy-imgui = { path = "../easy-imgui" }
easy-imgui-renderer = { path = "../easy-imgui-renderer" }

anyhow = "1"

glow = "0.12"
glutin = "0.30"
glutin-winit = "0.3"
raw-window-handle = "0.5"
arboard = { version = "3", optional = true, default_features = false }
winit = { version = "0.28", features = ["x11", "mint"] }

[dev-dependencies]
cstr = "*"
image = "*"
gilrs = "*"
