[package]
name = "easy-imgui-window"
version = "0.2.3"
edition = "2021"
description = "Default windowing for the easy-imgui crate using winit and easy-imgui-renderer"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/rodrigorc/easy-imgui-rs"
categories = ["gui"]
keywords = ["imgui", "ui", "graphics"]

[features]
default = ["clipboard"]
clipboard = ["dep:arboard"]
freetype = ["easy-imgui/freetype"]

# This is not really needed except for the examples/demo
# docking = ["easy-imgui/docking"]

[dependencies]
easy-imgui-sys = { version = "=0.2.3", path = "../easy-imgui-sys" }
easy-imgui = { version = "=0.2.3", path = "../easy-imgui" }
easy-imgui-renderer = { version = "=0.2.3", path = "../easy-imgui-renderer" }

anyhow = "1"

glutin = "0.31"
glutin-winit = "0.4"
raw-window-handle = "0.5"
arboard = { version = "3", optional = true, default_features = false }
winit = { version = "0.29", features = ["x11", "mint"] }

# For the examples
[dev-dependencies]
gilrs = "0.10"
anyhow = "1"
image = { version = "0.24" }
cstr = "0.2"
