[package]
name = "dear_imgui-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "imgui"

[dependencies]

[build-dependencies]
bindgen = "*"
cc = "*"
pkg-config = "*"

[features]
freetype = []
