[package]
name = "easy-imgui-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "imgui"

[dependencies]
mint = "0.5"

[build-dependencies]
bindgen = "0.68"
cc = "1"
pkg-config = "0.3"
xshell = "0.2"

[features]
freetype = []
