[package]
name = "easy-imgui-renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-imgui-sys = { path = "../easy-imgui-sys" }
easy-imgui = { path = "../easy-imgui" }

anyhow = "1"
cgmath = "0.18"
smallvec = "1"
glow = "0.13"
log = "*"
