[package]
name = "easy-imgui"
version = "0.1.1"
edition = "2021"
description = "Rust wrapper for the Dear ImGui library"
license = "MIT"
readme = "../README.md"
repository = "https://github.com/rodrigorc/easy-imgui-rs"
categories = ["gui"]
keywords = ["imgui", "ui", "graphics"]

[dependencies]
easy-imgui-sys = "=0.1.1"
paste = "1"
bitflags = "2"
cstr = "0.2"
mint = "0.5"
cgmath = { version = "0.18", features = ["mint"] }
image = { version = "0.24", default_features = false }

[features]
default = []
freetype = ["easy-imgui-sys/freetype"]
docking = ["easy-imgui-sys/docking"]

# For the examples
[dev-dependencies]
gilrs = "0.10"
easy-imgui-window = "0.1.1"
anyhow = "1"
