[package]
name = "easy-imgui"
version = "0.1.0"
edition = "2021"

[dependencies]
easy-imgui-sys = { path = "../easy-imgui-sys" }
paste = "1"
bitflags = "2"
cstr = "0.2"
mint = "0.5"
image = { version = "0.24", default_features = false }

[features]
default = []
freetype = ["easy-imgui-sys/freetype"]
docking = ["easy-imgui-sys/docking"]

# For the examples
[dev-dependencies]
gilrs = "0.10"
easy-imgui-window = { version="*", path="../easy-imgui-window" }
anyhow = "1"
