[package]
name = "easy-imgui"
version = "0.1.0"
edition = "2021"
description = "Rust wrapper for the Dear ImGui library"
license = "MIT"

[dependencies]
easy-imgui-sys = "=0.1.0"
paste = "1"
bitflags = "2"
cstr = "0.2"
mint = "0.5"
cgmath = { version = "0.18", features = ["mint"] }
image = { version = "0.24", default_features = false }

[features]
default = []
freetype = ["easy-imgui-sys/freetype"]
docking = ["easy-imgui-sys/docking"]

# For the examples
[dev-dependencies]
gilrs = "0.10"
easy-imgui-window = "0.1.0"
anyhow = "1"
